(() => {
'use strict';
const YT='https://music.youtube.com/youtubei/v1';
const MIRRORS=['https://backend.listenfree.in/api','https://backend2.listenfree.in/api'];
const STREAMS=['https://iv.datura.network/api/v1','https://invidious.nerdvpn.de/api/v1','https://pipedapi.moomoo.me'];
const CTX={client:{clientName:'WEB_REMIX',clientVersion:'1.20240101.01.00',hl:'en',gl:'US'}};
const audioCache=new Map(),searches=new Map();let originalHome=null,lastHome=null,homeRefresh=null;
const timeout=ms=>{try{return AbortSignal.timeout(ms)}catch(_){const c=new AbortController();setTimeout(()=>c.abort(),ms);return c.signal}};
const get=async(url,opts={},ms=2200)=>{const r=await fetch(url,{...opts,signal:timeout(ms),headers:{Accept:'application/json','Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()};
const post=(p,b)=>get(YT+p+'?alt=json',{method:'POST',body:JSON.stringify({context:CTX,...b})},2800);
const text=v=>Array.isArray(v)?v.map(x=>x?.text||'').join(''):String(v||'');
const vid=x=>x?.videoId||x?.playlistItemData?.videoId||x?.navigationEndpoint?.watchEndpoint?.videoId||x?.doubleTapCommand?.watchEndpoint?.videoId;
const track=x=>{if(!x)return null;if(x.musicTwoRowItemRenderer)x=x.musicTwoRowItemRenderer;const s=x.musicCardShelfRenderer||x,id=vid(s)||vid(x);if(!id)return null;const c=s.flexColumns||[],a=c[0]?.musicResponsiveListItemFlexColumnRenderer?.text?.runs||s.title?.runs||x.title?.runs||[],b=c[1]?.musicResponsiveListItemFlexColumnRenderer?.text?.runs||s.subtitle?.runs||x.subtitle?.runs||x.longBylineText?.runs||[],m=text(b.at(-1)?.text).match(/(\d+):(\d+)/);return{id:'synthetiq_music_gateway:yt:'+id,href:'synthetiq_music_gateway:yt:'+id,type:'track',title:text(a[0]?.text)||'Track',artist:text(b[0]?.text)||'Unknown Artist',album:b.length>2?text(b[2]?.text):undefined,durationSeconds:m?Number(m[1])*60+Number(m[2]):Number(s.lengthSeconds)||undefined}};
const tok=x=>x?.nextContinuationData?.continuation||x?.reloadContinuationData?.continuation||x?.continuationCommand?.token||x?.continuationEndpoint?.continuationCommand?.token||null;
function parseSearch(d){const ss=d?.contents?.tabbedSearchResultsRenderer?.tabs?.[0]?.tabRenderer?.content?.sectionListRenderer?.contents||[],o=[],seen=new Set();for(const s of ss){const a=s.musicShelfRenderer?.contents||(s.musicCardShelfRenderer?[s]:null)||s.itemSectionRenderer?.contents||[];for(const i of a){const t=track(i.musicResponsiveListItemRenderer||i);if(t&&!seen.has(t.id)){seen.add(t.id);o.push(t)}}}const sh=ss.find(s=>s.musicShelfRenderer);return{tracks:o,continuation:tok(sh?.musicShelfRenderer?.continuations?.[0])||tok(ss[0]?.musicShelfRenderer?.continuations?.[0])}};
function parseCont(d){const gs=[d?.continuationContents?.musicShelfContinuation?.contents,...(d?.onResponseReceivedActions||[]).flatMap(a=>[a?.appendContinuationItemsAction?.continuationItems,a?.reloadContinuationItemsCommand?.continuationItems])],o=[],seen=new Set();for(const a of gs)for(const i of a||[]){const t=track(i.musicResponsiveListItemRenderer||i.playlistPanelVideoRenderer||i);if(t&&!seen.has(t.id)){seen.add(t.id);o.push(t)}}const s=d?.continuationContents?.musicShelfContinuation;return{tracks:o,continuation:tok(s?.continuations?.[0])||tok(d?.onResponseReceivedActions?.[0]?.appendContinuationItemsAction)||tok(d?.onResponseReceivedActions?.[0]?.reloadContinuationItemsCommand)}};
async function expand(st,q){if(st.promise)return st.promise;st.promise=(async()=>{let c=null;try{for(let p=0;p<3&&st.tracks.length<150;p++){const d=p?c?await post('/search',{continuation:c}):null:await post('/search',{query:q,params:st.params});if(!d)break;const z=p?parseCont(d):parseSearch(d);for(const t of z.tracks)if(!st.seen.has(t.id)&&st.tracks.length<150){st.seen.add(t.id);st.tracks.push(t)}c=z.continuation;if(!c)break}}catch(_){}st.done=true;return st.tracks})();return st.promise}
async function search(q,page=0,options){q=String(q||'').trim();if(!q)return{ok:true,data:'[]'};page=Math.max(0,Number(page)||0);const k=q+'|'+String(typeof options==='string'?options:'');let st=searches.get(k);if(!st){st={tracks:[],seen:new Set(),done:false,promise:null,params:typeof options==='string'?options:undefined};searches.set(k,st)}expand(st,q);const deadline=page?1200:650,start=Date.now();while(!st.tracks.length&&!st.done&&Date.now()-start<deadline)await new Promise(r=>setTimeout(r,10));const part=st.tracks.slice(page*50,page*50+50);return{ok:true,data:JSON.stringify(part.length?part:st.tracks.slice(0,50))}}
async function audio(id){const v=String(id||'').includes(':yt:')?String(id).split(':yt:')[1]:/^[A-Za-z0-9_-]{11}$/.test(String(id||''))?String(id):null;if(!v)throw Error('unsupported id');const h=audioCache.get(v);if(h&&Date.now()-h.t<900000)return h.v;const routes=[post('/player',{videoId:v,contentCheckOk:true,racyCheckOk:true}),...STREAMS.map(b=>get(b+(b.includes('piped')?'/streams/':'/videos/')+encodeURIComponent(v),{},2200))];const d=await Promise.any(routes);const fs=d?.streamingData?.adaptiveFormats||d?.adaptiveFormats||d?.audioStreams||[];const f=fs.filter(x=>x?.url&&(!x.mimeType||String(x.mimeType).startsWith('audio/'))).sort((a,b)=>Number(b.bitrate||0)-Number(a.bitrate||0))[0];if(!f?.url)throw Error('no audio');const out={url:f.url,headers:{},mimeType:f.mimeType||'audio/mp4',extension:'mp4',title:d?.videoDetails?.title||d?.title||'Track',artist:d?.videoDetails?.author||d?.author||'Unknown Artist',album:'',artwork:d?.videoDetails?.thumbnail?.thumbnails?.at(-1)?.url||'',durationSeconds:Number(d?.videoDetails?.lengthSeconds)||undefined,quality:Math.round(Number(f.bitrate||0)/1000)+'kbps'};audioCache.set(v,{t:Date.now(),v:out});return out}
async function fastAudio(id,q,depth,opts={}){try{return{ok:true,data:JSON.stringify(await audio(id))}}catch(_){return{ok:false,error:{message:'No fast streaming route available for this track.'}}}}
async function home(page=0){if(Number(page)>0)return{ok:true,data:'[]'};if(lastHome){if(!homeRefresh&&originalHome)homeRefresh=Promise.resolve(originalHome(0)).then(v=>{if(v?.ok)lastHome=v}).catch(()=>{}).finally(()=>homeRefresh=null);return lastHome}if(!originalHome)return{ok:true,data:'[]'};const v=await Promise.race([originalHome(0),new Promise(r=>setTimeout(()=>r(null),900))]);if(v?.ok)lastHome=v;return v?.ok?v:{ok:true,data:'[]'}}
(async()=>{try{await import('./index.js')}catch(_){}originalHome=globalThis.homeSections;globalThis.searchResults=search;globalThis.searchAdvanced=(q,o)=>search(q,0,o);globalThis.extractAudioUrl=fastAudio;globalThis.homeSections=home})();
})();
